"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EXPENSE_TYPE = exports.TRAVEL_TYPE = exports.DEFAULT_ROUTE_FILTER = exports.ROUTE_FILTER = exports.EXPENSE_FILTER_tYPE = exports.DEFAULT_SECTION = exports.month = exports.MS_IN_DAY = exports.DEFAULT_IMG_URL = exports.GLOBAL_DB_VERSION = exports.CACHE_VERSION = exports.THEME = exports.USER_AUTH = exports.UNAUTHORIZED = exports.REFRESH_TOKEN = exports.ACCESS_TOKEN = void 0;
exports.ACCESS_TOKEN = 'access_token';
exports.REFRESH_TOKEN = 'refresh_token';
exports.UNAUTHORIZED = 'unauthorized';
exports.USER_AUTH = 'user';
exports.THEME = 'theme';
exports.CACHE_VERSION = 39;
exports.GLOBAL_DB_VERSION = 39;
exports.DEFAULT_IMG_URL = process.env.PUBLIC_URL + '/images/travel-placeholder.jpg';
exports.MS_IN_DAY = 24 * 60 * 60 * 1000;
exports.month = ['января', 'февраля', 'марта', 'апреля', 'мая', 'июня', 'июля', 'августа', 'сентября', 'октября', 'ноября', 'декабря'];
exports.DEFAULT_SECTION = 'misc';
exports.EXPENSE_FILTER_tYPE = 'expense_filter_type';
exports.ROUTE_FILTER = 'routeFilter';
exports.DEFAULT_ROUTE_FILTER = "byDays";
exports.TRAVEL_TYPE = 'travelType';
exports.EXPENSE_TYPE = 'expenseType';
