"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StoreName = void 0;
var StoreName;
(function (StoreName) {
    StoreName["SECTION"] = "Section";
    StoreName["LIMIT"] = "Limit";
    StoreName["EXPENSE"] = "Expense";
    StoreName["EXPENSES_ACTUAL"] = "expenses_actual";
    StoreName["EXPENSES_PLAN"] = "expenses_plan";
    StoreName["EXPENSES_ACTIONS"] = "expensesActions";
    StoreName["TRAVEL"] = "Travel";
    StoreName["TRAVEL_ACTIONS"] = "travelActions";
    StoreName["CHECKLIST"] = "Checklist";
    StoreName["TRAVEL_WAYPOINTS"] = "travel_waypoints";
    StoreName["ROUTE"] = "route";
    StoreName["STORE"] = "store";
    StoreName["CURRENCY"] = "Currency";
    StoreName["Photo"] = "Photo";
    StoreName["STORE_ACTIONS"] = "storeActions";
    StoreName["USERS"] = "User";
    StoreName["UPDATE"] = "update";
    StoreName["HOTELS"] = "Hotel";
    StoreName["ROAD"] = "ROAD";
    StoreName["APPOINTMENTS"] = "appointment";
    StoreName["ERRORS"] = "errors";
    StoreName["UPDATED_TRAVEL_INFO"] = "updatedTravelInfo";
    StoreName["ACTION"] = "Action";
    StoreName["MESSAGE"] = "Message";
    StoreName["PLACE"] = "Place";
    StoreName["UNINITIALIZED"] = "uninitialized";
})(StoreName || (exports.StoreName = StoreName = {}));
